
services:
###> shopware/core ###
  database:
    image: mysql:8-oracle
    environment:
      MYSQL_DATABASE: shopware
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${PWD}/../data/mysqldata:/var/lib/mysql:rw
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< shopware/core ###

###> shopware/elasticsearch ###
  opensearch:
    image: opensearchproject/opensearch:2
    volumes:
      - ${PWD}/../data/opensearch:/usr/share/opensearch/data
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
###< shopware/elasticsearch ###

volumes:
###> shopware/core ###
  db-data:
###< shopware/core ###

###> shopware/elasticsearch ###
  opensearch-data:
###< shopware/elasticsearch ###
